config/routes.rb
Rails.application.routes.draw do

  root 'pages#homepage'
  get 'about', to: 'pages#about'
  
  get 'signup', to: 'users#new'
  get 'users', to: 'users#index'
  
  resources :articles
  resources  :users, except: [:new]
  

end

app/models/article.rb
class Article < ActiveRecord::Base
    
    belongs_to :user
    
    validates :title, presence:true, length: { minimum: 3, maximum: 50 }
    validates :description, presence:true, length: {  minimum: 10, maximum: 300}
    validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    
    has_many :articles
    
    validates   :username, presence: true, uniqueness: { case_sensitive: false }, 
                length: { minimum: 3, maximum: 25 }
    
    VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    
    validates   :email, presence: true, length: { maximum: 105 },
                uniqueness: {case_sensitive: false},
                format: {with:  VALID_EMAIL_REGEX}
                
    has_secure_password
    
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    
    def index
        @articles = Article.all
    end
    
    def new
        @article = Article.new
    end
    
    def edit
        if Article.exists?(id: params[:id] )
            #@article = set_article
        else
            flash[:notice] = "Article not found"
            redirect_to articles_path
        end
    end
    
    def update
       # @article = set_article
        
        if @article.update(  article_params )
            flash[:success] = "Article was successfully updated.."
            redirect_to article_path(@article)
        else
            flash[:notice] = "Update has failed"
            render 'edit'
        end
    end
    
    def create
        @article = Article.new(article_params)
        @article.user = User.first
        if @article.save
            flash[:success] = "Article successfully created"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end
    
    def show
        if Article.exists?(id: params[:id] )
           # @article = set_article
        else
            flash[:notice] = "Article not found"
            redirect_to articles_path
        end
    end
    
    def destroy
        #@article = set_article
        
        
        if @article.destroy
            flash[:danger] = "Article has been successfully deleted"
            redirect_to articles_path
        else
            flash[:notice] = "Removal of article has failed"
            redirect_to articles_path
        end
    end
    
    private 
        def set_article
            if Article.exists?(id: params[:id] )
                @article = Article.find(params[:id])
            end
        end
        def article_params
            params.require(:article).permit(:title, :description)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
   def homepage
       
   end
   
   def about
       
       
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
   def index
   end
   
   def new
       @user = User.new
   end
   
   def create
      @user = User.new(user_params)
      
      if @user.save
         flash[:success] = "Welcome to the alpha blog #{@user.username}"
         redirect_to articles_path
      else
         flash[:notice] = "Registration has failed!"
         render 'new'
      end
   end
   
   def edit
      if User.exists?(id: params[:id] )
            @user = set_user
        else
            flash[:notice] = "User does not exist"
            redirect_to articles_path
      end
   end
   
   def update
      @user = User.find(params[:id])
      if @user.update(user_params)
         flash[:success] = @user.username + ", you have successfully updated your account"   
         redirect_to articles_path
      else
         flash[:notice] = "Something went wrong"
         render 'edit'
      end
   end
   
   private 
      def user_params
         params.require(:user).permit(:username, :email, :password)
      end
      def set_user
            if User.exists?(id: params[:id] )
                @user = User.find(params[:id])
            end
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
    <div class="col-xs-12">
        <%= form_for(@article, :html => { class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :title %>
                </div>
                <div class="col-sm-5">
                    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
                </div>
            </div>
            
           <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :description %>
                </div>
                <div class="col-sm-5">
                    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of article", autofocus: true %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit class: 'btn btn-primary btn-lg' %>
                </div>
            </div>
        <% end %>
        
        <div class="col-xs-4 col-xs-offset-4">
          [  <%= link_to "Back to articles", articles_path %> ]
        </div> 
    </div>
</div>

app/views/articles/edit.html.erb
<h2 class="col-sm-offset-2" align=center;>Edit article</h2>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>

<% @articles.each do |article| %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
                <div class="article-title">
                    <h3><%= link_to article.title, article_path(article) %></h3>
                </div>
                <div class="article-body">
                    <%= truncate(article.description, length: 100) %>
                    <div class="article-info">
                        <small>
                            Created by: <%= article.user.username if article.user %>,
                            <%= time_ago_in_words(article.created_at) %> ago,
                            last updated: <%= time_ago_in_words(article.updated_at) %>
                        </small>
                    </div>
                </div>
                <div class="article-action">
                    <%= link_to "Edit this article", 
                        edit_article_path(article), 
                        class: "btn btn-xs btn-primary" %> 
                    <%= link_to "Delete this article", 
                        article_path(article), 
                        method: :delete, 
                        data: {confirm: "Sure?"}, 
                        class: "btn btn-xs btn-danger" %>
                </div>
            </div>
        </div>
    </div>

    <% end %>
    </br>
<%= link_to 'Back to home', root_path %>

app/views/articles/new.html.erb
<h2 class="col-sm-offset-2" align=center;>Create an article</h2>



<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Article: <%= @article.title%></h1>

<div class="well col-xs-8">
    <h4 class="center"><strong>Description</strong></h4>
    <hr>
    Description: <%= @article.description%>

<div class="article-action">
    <%= link_to "Edit this article", 
        edit_article_path(@article), 
        class: "btn btn-xs btn-primary" %> 
    <%= link_to "Delete this article", 
        article_path(@article), 
        method: :delete, 
        data: {confirm: "Sure?"}, 
        class: "btn btn-xs btn-danger" %>
    <%= link_to "View all articles", 
        articles_path, 
        class: "btn btn-xs btn-success" %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
    <div class="row footer-sections">
        <div class="col-md-4 col-6 footer-section">
            <h3>Useful Links</h3>
            <ul>
                <li><%= link_to 'Articles', articles_path%></li>
                <li><%= link_to 'About', about_path%></li>
            </ul>
        </div>
        <div class="col-md-4 col-6 footer-section"></div>
        <div class="col-md-4 col-6 footer-section"></div>
    </div>
    <div class="footer-cp">
       <p> &copy; 2018 Alpha Blog </p>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name,msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
       </div>
    <% end %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "New Article", new_article_path %></li>
            <!--<li class="divider"></li>
            <li><a href="#">One more separated link</a></li>-->
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/messages'%>
    <div class="myContainer container">
        <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer'%>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<p style="max-width:500px;">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sapien turpis, consectetur blandit erat sed, pretium imperdiet dolor. Nulla commodo dignissim lacinia. Pellentesque metus justo, ullamcorper quis tempor quis, sollicitudin sit amet nulla. Phasellus ac orci libero. Phasellus at urna tincidunt, facilisis erat id, cursus turpis. Fusce ut erat feugiat, consequat ligula sit amet, tempus metus. Phasellus massa metus, vulputate a euismod at, ullamcorper at turpis. Maecenas dictum in nunc eu ullamcorper.
</p>


<%= link_to 'Homepage', root_path %>

app/views/pages/homepage.html.erb
<div class="myJumb jumbotron">
  <div class="container">
    <h1>Welcome to Alpha Blog!</h1>
    <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
    <p><%= link_to "Sign up now", 'signup', class: "btn btn-primary btn-lg" %></p>
  </div>
</div>

app/views/shared/_errors.html.erb
<%  if obj.errors.any? %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class='panel panel-danger'>
                <div class="panel-heading">
                    <h2 class="panel-title">
                            <%= pluralize(obj.errors.count, "error") %>
                            prohibited this article from being saved:
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">
    <div class="col-xs-12">
        <%= form_for(@user, :html => { class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :username%>
                </div>
                <div class="col-sm-5">
                    <%= f.text_field :username, class: "form-control", placeholder: "Username", autofocus: true %>
                </div>
            </div>
            
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :email%>
                </div>
                <div class="col-sm-5">
                    <%= f.email_field :email, class: "form-control", placeholder: "E-mail", autofocus: true %>
                </div>
            </div>
            
           <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :password %>
                </div>
                <div class="col-sm-5">
                    <%= f.password_field :password, class: "form-control", placeholder: "Password", autofocus: true %>    
                </div>
            </div>
            
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit(@user.new_record? ? "Sign up" : "Update", class: 'btn btn-primary btn-lg') %>
                </div>
            </div>
        <% end %>
        
    </div>
</div>

app/views/users/edit.html.erb
<h2 class="col-sm-offset-2" align=center;>Edit your account</h2>


<%= render 'form' %>

app/views/users/new.html.erb
<h2 class="col-sm-offset-2" align=center;>Signup for Alpha-Blog</h2>


<%= render 'form' %>